version: '3.8'

services:
  backend:
    build: .
    command: sh -c "uvicorn myapp.main:app --reload --port=8080 --host=0.0.0.0"
    ports:
      - 8080:8080
    volumes:
      - ./myapp:/code/myapp
    env_file:
      - .env

